# config/inferencer/conditional_diffusion/base.yaml
# @package inferencer

defaults:
  - /watch/train: conditional_diffusion
  - _self_

name: conditional_diffusion

diffusion:
  beta_schedule     : sigmoid
  timesteps         : 1000
  sampling_timesteps: 20

trainer:
  train_lr                 : 8e-5
  train_num_steps          : 100000
  save_and_sample_every    : 5000
  ema_decay                : 0.995
  amp                      : true
  calculate_fid            : false
