# config/inferencer/conditional_diffusion/complex.yaml
# @package inferencer

defaults:
  - base
  - /inferencer/network@network: unet_D128
  - _self_

trainer:
  train_batch_size         : 18
  gradient_accumulate_every: 5
