infer_model: conditional_diffusion

control:
  mode: epsilon_greedy_00

inference:
  model           : conditional_diffusion
  guidance_scale  : 0.2
  sample_image_num: 32

decision:
  mode : clip_ucb_raw
  param:
    ucb_lb: 0.5

segmentation:
  blue:
    target_mask   : [0.2, 0.8, 0.8]
    target_mask_lb: [-0.05, 0.55, 0.55]
    target_mask_ub: [0.45, 1.05, 1.05]

  red:
    target_mask   : [0.8, 0.2, 0.2]
    target_mask_lb: [0.7, 0.1, 0.1]
    target_mask_ub: [1.0, 0.4, 0.4]

  yellow:
    target_mask   : [0.8, 0.8, 0.2]
    target_mask_lb: [0.7, 0.7, 0.1]
    target_mask_ub: [1.0, 1.0, 0.8]
