infer_model: conditional_diffusion

control:
  mode: epsilon_greedy_00
  # mode: oracle_obs
  # mode: no_cond
  # mode: random
  # ---
  random_seed: null
  random_max_range_length: 3

inference:
  model             : conditional_diffusion
  guidance_scale    : 0.2
  sample_image_num  : 32
  sampling_timesteps: 20

decision:
  mode : clip_ucb_raw
  param:
    ucb_lb: 0.5
