infer_model: conditional_diffusion

control:
  mode: epsilon_greedy_00
  # mode: oracle_obs
  # mode: no_cond
  # mode: random
  # ---
  random_seed: null
  random_max_range_length: 3

inference:
  model             : conditional_diffusion
  guidance_scale    : 0.2

  # --------- settings for debug image saving during inference (optional) ---
  # sample_image_num  : 32
  # sampling_timesteps: 20

  sample_image_num  : 1
  sampling_timesteps: 1
  # --------------------------------------------------------------------------------


decision:
  mode : clip_ucb_raw
  param:
    ucb_lb: 0.5
