name : simple_A

cases:
  - name: Object_4
    dataset_format: boxy_generated_yaml
    dataset_dir   : /home/dev/workspace/dataset/nedo_product_dataset/dataset_5_12900k/geom_test_1/Boxy_0
    initial_global_action_range:
      start: 0
      stop : 4

  - name: Object_5
    dataset_format: boxy_generated_yaml
    dataset_dir   : /home/dev/workspace/dataset/nedo_product_dataset/dataset_5_12900k/geom_test_1/Boxy_1
    initial_global_action_range:
      start: 0
      stop : 4

  - name: Object_6
    dataset_format: boxy_generated_yaml
    dataset_dir   : /home/dev/workspace/dataset/nedo_product_dataset/dataset_5_12900k/geom_test_1/Boxy_2
    initial_global_action_range:
      start: 0
      stop : 4


