- name: Object_1
  dataset_dir: /home/dev/workspace/dataset/nedo/dataset_4_12900k/geom_test_3/Boxy_0
  initial_global_action_indices: [47, 46, 45, 44, 43, 42, 41]

- name: Object_2
  dataset_dir: /home/dev/workspace/dataset/nedo/dataset_4_12900k/geom_test_3/Boxy_1
  initial_global_action_indices: [47, 46, 45, 44, 43, 42, 41]

- name: Object_3
  dataset_dir: /home/dev/workspace/dataset/nedo/dataset_4_12900k/geom_test_3/Boxy_2
  initial_global_action_indices: [47, 46, 45, 44, 43, 42, 41]
