# config/eval/diffusion_1d/base.yaml
# @package eval

defaults:
  - /eval/task@task                      : default
  - /eval/execution_error@execution_error: default
  - _self_

# epoch: "100000"
epoch: "10"
# epoch: "1500"
