# config/eval/conditional_diffusion/complex.yaml
# @package eval

defaults:
  - base
  - /eval/common/cases@cases  : complex_paper_D # complex_paper
  - /eval/common/policy@policy: complex
  - /eval/method/conditional_diffusion/policy@policy
  - _self_

train_run_dir: /home/dev/workspace/dataset/nedo_dismantling_log/train/conditional_diffusion/unet_D128_T1000_S20_real_sheetsander_z49_20260504_202728
