defaults:
  - /dataset: celeba
  - _self_

name     : vaeac
USER_NAME: user
device   : "cuda:0"

model:
  name        : EncoderDecoderNet
  last_layer  : tanh
  inp_channels: 3
  n_hidden    : 32
  fc_hidden   : 100
  fc_out      : 50
  optimizer   : adam
  lr          : 0.00005
  beta1       : 0.9
  beta2       : 0.999
  scheduler   : step
  decay-steps : 500
  decay-factor: 0.995
  weight-decay: 0.00001
  init        : orthogonal
  loss        : mse
  lr_override : false

# regularization parameter in model training
reg:
  lambda_kl : 1
  lambda_reg: 1
  sigma_m   : 10000
  sigma_s   : 0.0001
  apply_reg : true


trainer:
  pretrained  : null
  train       :
    train_step               : 800000
    batch_size               : 96
    gradient_accumulate_every: 2
    shuffle                  : true
    step-log                 : 5
    peek-validation          : 10000

log:
  logbase : logs
  prefix  : vaeac/
  tag     : H100_simple_models_dataset_13901k_v1
  exp_name: null
  layout  : "dataset"
  suffix  :

# config/task/vaeac.yaml など
watch:
  - { key: log.prefix, label: "" }
  - { key: dataset.image_size, label: "D" }
  - { key: log.tag, label: "" }
