# config/inferencer/vaeac/complex.yaml
# @package inferencer

defaults:
  - base
  - _self_

network:
  n_hidden : 96
  fc_hidden: 300
  fc_out   : 150
  chan     : 43

trainer:
  train:
    batch_size               : 18
    gradient_accumulate_every: 5
