# config/inferencer/vaeac/simple.yaml
# @package inferencer

defaults:
  - base
  - _self_

network:
  n_hidden : 32
  fc_hidden: 100
  fc_out   : 50
  chan     : 8

trainer:
  train:
    batch_size               : 96
    gradient_accumulate_every: 2
