# config/usecase/train/complex/i2sb.yaml
# @package usecase

defaults:
  - /inferencer/i2sb@inferencer: complex
  - /dataset                   : complex_2d_sheetsander
  - /log                       : train
  - /path                      : local
  - _self_

name  : train
device: cuda:0
