# config/usecase/train/complex/vaeac.yaml
# @package usecase

defaults:
  - /inferencer/vaeac@inferencer: complex
  - /dataset    : complex_2d
  - /log        : train
  - /path       : local
  - _self_

name  : train
device: cuda:0
