# config/usecase/eval/complex/conditional_diffusion.yaml
# @package usecase

defaults:
  - /eval/method/conditional_diffusion@eval: complex
  - /env                                   : complex
  - /watch/eval: conditional_diffusion
  - /path      : local
  - /log       : eval
  - _self_

name      : eval
device    : cuda:0
