# config/usecase/eval/complex/conditional_diffusion.yaml
# @package usecase

defaults:
  - /eval/conditional_diffusion@eval: complex
  - /watch/eval: conditional_diffusion_eval
  - /env       : complex
  - /path      : local
  - /log       : eval
  - _self_

name      : eval
device    : cuda:0
