# config/usecase/eval/complex/diffusion_1d.yaml
# @package usecase

defaults:
  - /eval/method/diffusion_1d@eval: complex
  - /env                          : complex
  - /watch/eval: diffusion_1d
  - /path      : local
  - /log       : eval
  - _self_

name      : eval
device    : cuda:0
