# config/usecase/eval/complex/vaeac.yaml
# @package usecase

defaults:
  - /eval/vaeac@eval: complex
  - /env            : complex
  - /watch/eval: vaeac_eval
  - /path      : local
  - /log       : eval
  - _self_

name      : eval
device    : cuda:0
