# config/usecase/eval/complex/vaeac.yaml
# @package usecase

defaults:
  - /eval/method/vaeac@eval: complex
  - /env                   : complex
  - /watch/eval: vaeac
  - /path      : local
  - /log       : eval
  - _self_

name      : eval
device    : cuda:0
