# config/eval/conditional_diffusion/complex.yaml
# @package eval

defaults:
  - base
  - /eval/cases@cases  : complex_paper
  - /eval/policy@policy: complex
  - /eval/policy/conditional_diffusion@policy: base
  - _self_

train_run_dir: /home/dev/workspace/dataset/nedo_dismantling_log/train/conditional_diffusion/unet_D128_T1000_S20_real_sheetsander_z49_20260504_202728
