defaults:
  - /path                    : local
  - /log                     : eval
  - /watch                   : eval_base
  # - /inferencer              : conditional_diffusion
  # - /network@_global_.network: unet_dim64
  - /eval                    : default
  - /env                     : complex
  # - /dataset                 : celeba
  - _self_

name      : eval
device    : cuda:0
