defaults:
  - /path                    : local
  - /log                     : eval
  - /watch                   : eval_base
  - /inferencer              : conditional_diffusion
  - /network@_global_.network: unet
  - /eval                    : default
  - /env                     : default
  - /dataset                 : celeba
  - _self_

name      : eval
device    : cuda:0
