defaults:
  - /path                    : local
  - /log                     : eval
  - /watch/eval              : conditional_diffusion_eval
  - /eval                    : default
  - /env                     : simple
  - _self_

name      : eval
device    : cuda:0
