defaults:
  - /path      : local
  - /log       : eval
  - /watch     : eval_base
  - /inferencer: conditional_image_diffusion  # ここは評価対象のアルゴリズム
  - /eval      : default
  - /env       : default
  - /dataset   : celeba
  - _self_

name: eval
device: cuda:0
