defaults:
  - /eval       : simple_conditional_diffusion
  - /watch/eval : conditional_diffusion_eval
  - /path       : local
  - /log        : eval
  - /env        : simple
  - _self_

name      : eval
device    : cuda:0
