defaults:
  - /path                    : local
  - /log                     : eval
  - /watch/eval              : conditional_diffusion_eval
  - /eval                    : complex
  - /env                     : complex
  - _self_

name      : eval
device    : cuda:0
