defaults:
  - /inferencer : vaeac_simple
  - /dataset    : simple
  - /log        : train
  - /path       : local
  - /watch/train: vaeac
  - _self_

device: cuda:0

log:
  prefix  : train/vaeac
  exp_name: null
  layout  : dataset
  suffix  : null
