# scripts/analysis/plot_task_metrics.py
from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd


METRIC_SPECS = [
    {
        "name"     : "cutting_error_volume",
        "label"    : "Cutting Error Volume [voxels]",
        "direction": "lower is better",
    },
    {
        "name"     : "part_remaining_rate",
        "label"    : "Part Remaining Rate [%]",
        "direction": "higher is better",
    },
    {
        "name"     : "part_occupancy_rate",
        "label"    : "Part Occupancy Rate [%]",
        "direction": "higher is better",
    },
    {
        "name"     : "episode_cumulative_normalized_cutting_error_rate",
        "label"    : "Normalized Cutting Error Rate [%]",
        "direction": "lower is better",
    },
]


def plot_metric(
    summary_df: pd.DataFrame,
    metric_name: str,
    ylabel: str,
    title_suffix: str,
    out_path: Path,
) -> None:
    mean_col = f"{metric_name}_mean"
    sem_col = f"{metric_name}_sem"

    if mean_col not in summary_df.columns:
        raise KeyError(f"Missing column: {mean_col}")

    fig, ax = plt.subplots(figsize=(6.0, 4.0))

    for eta, group in summary_df.groupby("eta"):
        group = group.sort_values("delta")

        x = group["delta"].to_numpy()
        y = group[mean_col].to_numpy()

        if sem_col in group.columns:
            yerr = group[sem_col].to_numpy()
        else:
            yerr = None

        ax.errorbar(
            x,
            y,
            yerr=yerr,
            marker="o",
            capsize=4,
            label=f"η = {eta:g}",
        )

    ax.set_xlabel("Maximum execution error Δ [voxels]")
    ax.set_ylabel(ylabel)
    ax.set_title(title_suffix)
    ax.grid(True, alpha=0.3)
    ax.legend()
    fig.tight_layout()

    fig.savefig(out_path, dpi=300)
    plt.close(fig)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--summary_csv",
        type=Path,
        required=True,
        help="summary_metrics.csv generated by aggregate_task_metrics.py",
    )
    parser.add_argument(
        "--out_dir",
        type=Path,
        required=True,
        help="Directory to save figures.",
    )
    parser.add_argument(
        "--format",
        type=str,
        default="png",
        choices=["png", "pdf", "svg"],
    )

    args = parser.parse_args()

    args.out_dir.mkdir(parents=True, exist_ok=True)

    summary_df = pd.read_csv(args.summary_csv)

    required_cols = {"eta", "delta"}
    missing = required_cols - set(summary_df.columns)
    if missing:
        raise ValueError(f"summary_csv is missing columns: {missing}")

    for spec in METRIC_SPECS:
        metric_name = spec["name"]
        out_path = args.out_dir / f"{metric_name}_vs_execution_error.{args.format}"

        plot_metric(
            summary_df=summary_df,
            metric_name=metric_name,
            ylabel=spec["label"],
            title_suffix=f"{spec['label']} ({spec['direction']})",
            out_path=out_path,
        )

        print(f"[OK] Saved figure: {out_path}")


if __name__ == "__main__":
    main()
