# scripts/analysis/plot_task_metrics.py
from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib.pyplot as plt
import pandas as pd


METRIC_SPECS = [
    {
        "name"     : "cutting_error_volume",
        "label"    : "Cutting Error Volume [voxels]",
        "direction": "lower is better",
    },
    {
        "name"     : "part_remaining_rate",
        "label"    : "Part Remaining Rate [%]",
        "direction": "higher is better",
    },
    {
        "name"     : "part_occupancy_rate",
        "label"    : "Part Occupancy Rate [%]",
        "direction": "higher is better",
    },
]

AXIS_LABELS = {
    "delta"             : "Maximum execution error Δ [voxels]",
    "eta"               : "Cutting-risk threshold (η)",
    "guidance_scale"    : "CFG guidance scale (w)",
    "sample_image_num"  : "Number of generated samples (M)",
    "sampling_timesteps": "DDIM sampling steps",
}


def plot_metric(
    summary_df: pd.DataFrame,
    metric_name: str,
    ylabel: str,
    title_suffix: str,
    out_path: Path,
    x_axis: str,
    group_by: str | None,
) -> None:
    mean_col = f"{metric_name}_mean"
    sem_col = f"{metric_name}_sem"

    if mean_col not in summary_df.columns:
        raise KeyError(f"Missing column: {mean_col}")

    if x_axis not in summary_df.columns:
        raise KeyError(f"Missing x_axis column: {x_axis}")

    if group_by is not None and group_by not in summary_df.columns:
        raise KeyError(f"Missing group_by column: {group_by}")

    fig, ax = plt.subplots(figsize=(5.0, 4.0))

    if group_by is None:
        plot_groups = [(None, summary_df)]
    else:
        plot_groups = list(summary_df.groupby(group_by, dropna=False))

    print(f"\nPlotting metric '{metric_name}' vs '{x_axis}'")
    for group_value, group in plot_groups:

        group = group.sort_values(x_axis)

        x = group[x_axis].to_numpy()
        y = group[mean_col].to_numpy()

        yerr = group[sem_col].to_numpy() if sem_col in group.columns else None

        label = None
        if group_by is not None:
            label = f"{AXIS_LABELS.get(group_by, group_by)} = {group_value:g}"

        ax.errorbar(
            x,
            y,
            yerr=yerr,
            marker="o",
            capsize=4,
            label=label,
        )

        print(f"group_value = {group_value} | x = {x} | y = {y} | yerr = {yerr}")
        # import ipdb; ipdb.set_trace()

    ax.set_xlabel(AXIS_LABELS.get(x_axis, x_axis), fontsize=14)
    ax.set_ylabel(ylabel, fontsize=14)

    x_tick_values = sorted(summary_df[x_axis].dropna().unique())
    ax.set_xticks(x_tick_values)

    if x_axis in ["delta", "sample_image_num", "sampling_timesteps"]:
        ax.set_xlim(min(x_tick_values) - 0.1, max(x_tick_values) + 0.1)

    ax.tick_params(axis="x", labelsize=12)
    ax.tick_params(axis="y", labelsize=12)

    ax.grid(True, alpha=0.3)

    if group_by is not None:
        ax.legend(fontsize=12)

    fig.tight_layout()
    fig.savefig(out_path, dpi=300)
    plt.close(fig)



def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--summary_csv",
        type=Path,
        required=True,
        help="summary_metrics.csv generated by aggregate_task_metrics.py",
    )
    parser.add_argument(
        "--out_dir",
        type=Path,
        required=True,
        help="Directory to save figures.",
    )
    parser.add_argument(
        "--format",
        type=str,
        default="png",
        choices=["png", "pdf", "svg"],
    )
    parser.add_argument(
        "--x_axis",
        type=str,
        default="delta",
        help=(
            "Column to use as x-axis. "
            "Examples: delta, guidance_scale, sample_image_num, sampling_timesteps."
        ),
    )
    parser.add_argument(
        "--group_by",
        type=str,
        default=None,
        help=(
            "Optional column for grouping lines. "
            "Use eta for eta-delta sweep. Omit for one-parameter sensitivity."
        ),
    )


    args = parser.parse_args()

    args.out_dir.mkdir(parents=True, exist_ok=True)

    summary_df = pd.read_csv(args.summary_csv)


    required_cols = {args.x_axis}
    if args.group_by is not None:
        required_cols.add(args.group_by)

    missing = required_cols - set(summary_df.columns)
    if missing:
        raise ValueError(f"summary_csv is missing columns: {missing}")


    for spec in METRIC_SPECS:
        metric_name = spec["name"]
        # out_path = args.out_dir / f"{metric_name}_vs_execution_error.{args.format}"
        out_path = args.out_dir / f"{metric_name}_vs_{args.x_axis}.{args.format}"

        plot_metric(
            summary_df=summary_df,
            metric_name=metric_name,
            ylabel=spec["label"],
            title_suffix=f"{spec['label']} ({spec['direction']})",
            out_path=out_path,
            x_axis=args.x_axis,
            group_by=args.group_by,
        )

        print(f"[OK] Saved figure: {out_path}")


if __name__ == "__main__":
    main()
