# # config/eval/policy/method/vaeac.yaml
# # @package eval.policy

# infer_model: vaeac

# inference:
#   model: vaeac

#   # build_policy_config が現状常に読むため、ダミーとして残す
#   guidance_scale    : 0.0
#   sampling_timesteps: 1
