# config/eval/method/diffusion_1d/base.yaml
# @package eval

defaults:
  - /eval/common/task@task                      : default
  - /eval/common/execution_error@execution_error: default
  - _self_

epoch: "100000"
