# config/eval/diffusion_1d/simple.yaml
# @package eval

defaults:
  - base
  - /eval/common/cases@cases  : simple_paper
  - /eval/common/policy@policy: simple
  - /eval/method/diffusion_1d/policy@policy
  - _self_

train_run_dir: /home/dev/workspace/dataset/nedo_dismantling_log/train/diffusion_1d/pointnet1d_D64_T1000_S20_simple_1d_20260605_110050
