# config/usecase/train/simple/diffusion_1d.yaml
# @package usecase

defaults:
  - /inferencer/diffusion_1d@inferencer: simple
  - /dataset    : simple_1d
  - /log        : train
  - /path       : local
  - _self_

name  : train
device: cuda:0
