# config/eval/policy/default.yaml

control:
  mode: epsilon_greedy_00
  # mode: oracle_obs
  # mode: no_cond
  # mode: random
  # ---
  random_seed: null
  random_max_range_length: 3


inference:
  sample_image_num: 32 # モデル非依存で共通に使う値

decision:
  mode : clip_ucb_raw
  param:
    # ------
    # ucb_lb: 0.0
    ucb_lb: 0.5
    # ucb_lb: 1.0

    # ------
    safety_margin_voxels: 2
