# config/inferencer/diffusion_1d/simple.yaml
# @package inferencer

defaults:
  - base
  # - /inferencer/network@network: unet1d_D64
  - /inferencer/network@network: pointnet1d_D64
  - _self_

trainer:
  train_batch_size         : 96
  gradient_accumulate_every: 2
