watch_base:
  - key: log.prefix
    label: ''
    as_dir: true

  - kind: basename
    key: eval.train_run_dir
    label: ''
    as_dir: true

  - key: eval.cases.name
    label: ''

  - key: eval.task.task_step
    label: T

  - key: eval.task.num_episodes
    label: N

  - key: eval.policy.decision.param.ucb_lb
    label: eta
    value_format: safe_float

  - key: eval.execution_error.max_abs_shift
    label: D

  - key: eval.policy.inference.guidance_scale
    label: w
    value_format: safe_float

  - key: eval.policy.inference.sample_image_num
    label: M

  - key: eval.policy.inference.sampling_timesteps
    label: S

  - key: eval.epoch
    label: E

  - key: log.tag
    label: ''
