# config/usecase/eval/simple/conditional_diffusion.yaml
# @package usecase

defaults:
  - /eval/conditional_diffusion@eval: simple
  - /watch/eval: conditional_diffusion_eval
  - /env       : simple
  - /path      : local
  - /log       : eval
  - _self_

name      : eval
device    : cuda:0
