# config/usecase/eval/simple/conditional_diffusion.yaml
# @package usecase

defaults:
  - /eval/method/conditional_diffusion@eval: simple
  - /env                                   : simple
  - /watch/eval: conditional_diffusion
  - /path: local
  - /log : eval
  - _self_

name  : eval
device: cuda:0
