# config/usecase/eval/simple/diffusion_1d.yaml
# @package usecase

defaults:
  - /eval/method/diffusion_1d@eval: simple
  - /env                          : simple
  - /watch/eval: diffusion_1d
  - /path: local
  - /log : eval
  - _self_

name  : eval
device: cuda:0
