# config/usecase/eval/simple/diffusion_1d.yaml
# @package usecase

defaults:
  - /eval/diffusion_1d@eval: simple
  - /watch/eval: diffusion_1d
  - /env       : simple
  - /path      : local
  - /log       : eval
  - _self_

name      : eval
device    : cuda:0
