# config/usecase/eval/simple/vaeac.yaml
# @package usecase

defaults:
  - /eval/vaeac@eval: simple
  - /watch/eval: vaeac_eval
  - /env       : simple
  - /path      : local
  - /log       : eval
  - _self_

name      : eval
device    : cuda:0
