# config/usecase/eval/simple/vaeac.yaml
# @package usecase

defaults:
  - /eval/method/vaeac@eval: simple
  - /env                   : simple
  - /watch/eval: vaeac
  - /path: local
  - /log : eval
  - _self_

name  : eval
device: cuda:0
