from typing import Protocol, Any

class TrainMethodBuilder(Protocol):
    def build_dataset(self) -> Any: ...
    def build_model(self)   -> Any: ...
    def build_method(self)  -> Any: ...
    def build_trainer(self) -> Any: ...
