name     : conditional_diffusion
USER_NAME: user

diffusion:
  beta_schedule     : sigmoid
  timesteps         : 1000
  sampling_timesteps: 20


network:
  architecture  : unet
  # ----
  dim           : 64
  dim_mults     : [1, 2, 4, 8]
  flash_attn    : true
  self_condition: false

trainer:
  train_batch_size         : 96
  train_lr                 : 8e-5
  train_num_steps          : 800000
  save_and_sample_every    : 2000
  gradient_accumulate_every: 2
  ema_decay                : 0.995
  amp                      : true
  calculate_fid            : false

watch:
  - { key: log.prefix, label: "" }
  - { key: log.n_diffusion_step, label: "T" }
  - { key: diffusion.sampling_timestep, label: "S" }
  - { key: dataset.image_size, label: "D" }
  - { key: log.tag, label: "" }

