defaults:
  # - /watch/train: conditional_diffusion
  - network : unet_D128 # <--
  - _self_

name     : conditional_diffusion
USER_NAME: user

diffusion:
  beta_schedule     : sigmoid
  timesteps         : 1000
  sampling_timesteps: 20

trainer:
  train_batch_size         : 18 # <--
  train_lr                 : 8e-5
  train_num_steps          : 800000
  save_and_sample_every    : 2000
  gradient_accumulate_every: 5 # <--
  ema_decay                : 0.995
  amp                      : true
  calculate_fid            : false

