defaults:
  - /watch/train: vaeac
  - _self_

name: vaeac

network:
  name        : EncoderDecoderNet
  last_layer  : tanh
  inp_channels: 3
  optimizer   : adam
  lr          : 0.00005
  beta1       : 0.9
  beta2       : 0.999
  scheduler   : step
  decay-steps : 500
  decay-factor: 0.995
  weight-decay: 0.00001
  init        : orthogonal
  loss        : mse
  lr-override : false

reg:
  lambda_kl : 1
  lambda_reg: 1
  sigma_m   : 10000
  sigma_s   : 0.0001
  apply_reg : true

trainer:
  pretrained: null
  train:
    train_step               : 100000
    batch_size               : 96
    gradient_accumulate_every: 2
    shuffle                  : true
    step-log                 : 5
    peek-validation          : 10000

