defaults:
  - cases : simple
  - policy: default

eval_data_path: /home/dev/.../geom_test_1

train_run_dir: /home/dev/workspace/denoising_diffusion_pytorch/logs/Image_diffusion_2D/train/D64

epoch   : "2000"  #"10000"

task_step: 8
observation_mode: partial_obs
num_episodes: 6 # iter: [0, 6] # Objectごとの評価回数

