defaults:
  - cases : simple
  - policy: default

# ---- training run directory settings ----
# train_run_dir: /home/dev/workspace/denoising_diffusion_pytorch/logs/Image_diffusion_2D/train/D64
# train_run_dir : /home/dev/workspace/dataset/nedo_dismantling_log/Image_diffusion_2D/train/D64
# train_run_dir : /home/dev/workspace/dataset/nedo_dismantling_log/Image_diffusion_2D/train/D344
train_run_dir : /home/dev/workspace/dataset/nedo_dismantling_log/train/conditional_diffusion/unet_D64_T1000_S20_simple_20260504_160530

# ------ epoch and evaluation settings ------
# epoch   : "2000"
epoch   : "60000"

# ------ eval settings ------
task_step       : 8
observation_mode: partial_obs
num_episodes    : 6            # iter: [0, 6] # Objectごとの評価回数

