defaults:
  - cases : simple
  - policy: default

# ---- training run directory settings ----
# train_run_dir : /home/dev/workspace/dataset/nedo_dismantling_log/train/conditional_diffusion/unet_D64_T1000_S20_simple_20260504_204336
train_run_dir : /home/dev/workspace/dataset/nedo_dismantling_log/train/conditional_diffusion/unet_D64_T1000_S20_simple_20260504_204421

# ------ epoch and evaluation settings ------
epoch   : "200000"

# ------ eval settings ------
task_step       : 8
observation_mode: partial_obs
num_episodes    : 6            # iter: [0, 6] # Objectごとの評価回数

